version: '3'
services:
  springapp:
    image: 251219981642/appimage:latest
    restart: always
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb123
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=devdb
     - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    restart: always

  web:
    image: 251219981642/webimage:latest
    ports:
      - "8081:8081"
volumes:
  mongodb: {}
